baseURL = "https://woowa-techcamp-2024.github.io/dev-log"
languageCode = "ko-kr"
title = "ìš°í…Œìº  ê¸°ìˆ  ë¸”ë¡œê·¸"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true
contentDir = "content"
publishdir = "./docs/"

[params]
  author = "Yoda Codd"
  description = "ìš°ì•„í•˜ê²Œ í•¨ê»˜ ì„±ì¥í•˜ëŠ” ê°œë°œì ë¡œê·¸"
  keywords = "blog, web, backend"
  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€"
  favicon = "/dev-log//images/favicon.png"
  avatar = "/dev-log/images/woowa.png"
  headerIcon = "/dev-log/images/woowacon.png"
  location = "Korea"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
